### ISSUE TITLE
java.util.MissingFormatArgumentException: Format specifier: 2F

### ISSUE THREAD

**Issue by Secretbox1987** [halilozercan/BetterVideoPlayer#24]
java.util.MissingFormatArgumentException: Format specifier: 2F
                                                                              at java.util.Formatter.getArgument(Formatter.java:1111)
                                                                              at java.util.Formatter.doFormat(Formatter.java:1076)
                                                                              at java.util.Formatter.format(Formatter.java:1042)
                                                                              at java.util.Formatter.format(Formatter.java:1011)
                                                                              at java.lang.String.format(String.java:1554)
                                                                              at java.lang.String.format(String.java:1528)
                                                                              at com.halilibo.bettervideoplayer.BetterVideoPlayer.LOG(BetterVideoPlayer.java:871)
                                                                              at com.halilibo.bettervideoplayer.BetterVideoPlayer.prepare(BetterVideoPlayer.java:323)
                                                                              at com.halilibo.bettervideoplayer.BetterVideoPlayer.onSurfaceTextureAvailable(BetterVideoPlayer.java:562)
                                                                              at android.view.TextureView.getHardwareLayer(TextureView.java:368)
                                                                              at android.view.View.updateDisplayListIfDirty(View.java:15233)
                                                                              at android.view.View.draw(View.java:16029)
                                                                              at android.view.ViewGroup.drawChild(ViewGroup.java:3654)
                                                                              at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3444)
                                                                              at android.view.View.updateDisplayListIfDirty(View.java:15251)
                                                                              at android.view.View.draw(View.java:16029)
                                                                              at android.view.ViewGroup.drawChild(ViewGroup.java:3654)
                                                                              at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3444)
                                                                              at android.view.View.draw(View.java:16262)
                                                                              at android.view.View.updateDisplayListIfDirty(View.java:15256)
                                                                              at android.view.View.draw(View.java:16029)
                                                                              at android.view.ViewGroup.drawChild(ViewGroup.java:3654)
                                                                              at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3444)
                                                                              at android.view.View.draw(View.java:16262)
                                                                              at android.view.View.updateDisplayListIfDirty(View.java:15256)
                                                                              at android.view.View.draw(View.java:16029)
                                                                              at android.view.ViewGroup.drawChild(ViewGroup.java:3654)
                                                                              at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3444)
                                                                              at android.view.View.updateDisplayListIfDirty(View.java:15251)
                                                                              at android.view.View.draw(View.java:16029)
                                                                              at android.view.ViewGroup.drawChild(ViewGroup.java:3654)
                                                                              at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3444)
                                                                              at android.view.View.updateDisplayListIfDirty(View.java:15251)
                                                                              at android.view.View.draw(View.java:16029)
                                                                              at android.view.ViewGroup.drawChild(ViewGroup.java:3654)
                                                                              at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3444)
                                                                              at android.view.View.updateDisplayListIfDirty(View.java:15251)
                                                                              at android.view.View.draw(View.java:16029)
                                                                              at android.view.ViewGroup.drawChild(ViewGroup.java:3654)
                                                                              at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3444)
                                                                              at android.view.View.draw(View.java:16262)
                                                                              at android.view.View.updateDisplayListIfDirty(View.java:15256)
                                                                              at android.view.View.draw(View.java:16029)
                                                                              at android.view.ViewGroup.drawChild(ViewGroup.java:3654)
                                                                              at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3444)
                                                                              at android.view.View.updateDisplayListIfDirty(View.java:15251)
                                                                              at android.view.View.draw(View.java:16029)
                                                                              at android.view.ViewGroup.drawChild(ViewGroup.java:3654)
                                                                              at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3444)
                                                                              at android.view.View.updateDisplayListIfDirty(View.java:15251)
                                                                              at android.view.View.draw(View.java:16029)
                                                                              at android.view.ViewGroup.drawChild(ViewGroup.java:3654)
                                                                              at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3444)
                                                                              at android.view.View.updateDisplayListIfDirty(View.java:15251)
                                                                              at android.view.View.draw(View.java:16029)
                                                                              at android.view.ViewGroup.drawChild(ViewGroup.java:3654)
                                                                              at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3444)
                                                                              at android.view.View.updateDisplayListIfDirty(View.java:15251)
                                                                              at android.view.View.draw(View.java:16029)
                                                                              at android.view.ViewGroup.drawChild(ViewGroup.java:3654)
                                                                              at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3444)
                                                                              at android.view.View.updateDisplayListIfDirty(View.java:15251)
                                                                              at android.view.View.draw(View.java:16029)
                                                                              at android.view.ViewGroup.drawChild(ViewGroup.java:3654)
                                                                              at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3444)
                                                                              at android.view.View.updateDisplayListIfDirty(View.java:15251)
                                                                              at android.view.View.draw(View.java:16029)
                                                                              at android.view.ViewGroup.drawChild(ViewGroup.java:3654)

**Comment by VAHID-ZAHEDI** [comment]
this is my problem

**Comment by halilozercan** [comment]
This issue is cause by a log method. It was implemented in the original version of the library. I've tried to fix it many times but once in a while this issue pops up again. I will write a log method from ground up that can support various encoding styles.
