### ISSUE TITLE
BetterVideoPlayer.prepare

### ISSUE THREAD

**Issue by ajaystha005** [halilozercan/BetterVideoPlayer#40]
I am getting most of the time
Fatal Exception: java.lang.IllegalStateException
       at android.media.MediaPlayer.nativeSetDataSource(MediaPlayer.java)
       at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1204)
       at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1188)
       at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1142)
       at com.halilibo.bettervideoplayer.BetterVideoPlayer.prepare(BetterVideoPlayer.java:357)
       at com.halilibo.bettervideoplayer.BetterVideoPlayer.onSurfaceTextureAvailable(BetterVideoPlayer.java:667)
       at android.view.TextureView.getHardwareLayer(TextureView.java:370)
       at android.view.View.updateDisplayListIfDirty(View.java:15443)
       at android.view.View.getDisplayList(View.java:15488)
       at android.view.View.draw(View.java:16258)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3713)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3506)
       at android.view.View.updateDisplayListIfDirty(View.java:15461)
       at android.view.View.getDisplayList(View.java:15488)
       at android.view.View.draw(View.java:16258)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3713)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3506)
       at android.view.View.draw(View.java:16539)
       at android.view.View.updateDisplayListIfDirty(View.java:15466)
       at android.view.View.getDisplayList(View.java:15488)
       at android.view.View.draw(View.java:16258)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3713)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3506)
       at android.view.View.updateDisplayListIfDirty(View.java:15461)
       at android.view.View.getDisplayList(View.java:15488)
       at android.view.View.draw(View.java:16258)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3713)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3506)
       at android.view.View.updateDisplayListIfDirty(View.java:15461)
       at android.view.View.getDisplayList(View.java:15488)
       at android.view.View.draw(View.java:16258)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3713)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3506)
       at android.view.View.updateDisplayListIfDirty(View.java:15461)
       at android.view.View.getDisplayList(View.java:15488)
       at android.view.View.draw(View.java:16258)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3713)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3506)
       at android.view.View.updateDisplayListIfDirty(View.java:15461)
       at android.view.View.getDisplayList(View.java:15488)
       at android.view.View.draw(View.java:16258)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3713)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3506)
       at android.view.View.draw(View.java:16539)
       at android.widget.FrameLayout.draw(FrameLayout.java:598)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:3111)
       at android.view.View.updateDisplayListIfDirty(View.java:15466)
       at android.view.View.getDisplayList(View.java:15488)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:309)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:315)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:354)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2956)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2753)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2339)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1314)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7057)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:829)
       at android.view.Choreographer.doCallbacks(Choreographer.java:606)
       at android.view.Choreographer.doFrame(Choreographer.java:576)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:815)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6934)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

**Comment by asadwaheed1** [comment]
I am also getting it on latest version
