### ISSUE TITLE
UDP FileNotFoundException

### ISSUE THREAD

**Issue by ZeeshanArid** [halilozercan/BetterVideoPlayer#54]
04-16 21:34:08.399 8036-8036/org.zaryans.bestplayertest D/MediaPlayer: setDataSource IOException | SecurityException happend : 
    java.io.FileNotFoundException: No content provider: udp://@xxx.x.x:3000
        at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1139)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:990)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:913)
        at android.media.MediaPlayer.attemptDataSource(MediaPlayer.java:1110)
        at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1101)
        at com.halilibo.bettervideoplayer.BetterVideoPlayer.prepare(BetterVideoPlayer.java:360)
        at com.halilibo.bettervideoplayer.BetterVideoPlayer.onSurfaceTextureAvailable(BetterVideoPlayer.java:667)
        at android.view.TextureView.getHardwareLayer(TextureView.java:390)
        at android.view.TextureView.draw(TextureView.java:339)
        at android.view.View.updateDisplayListIfDirty(View.java:17537)
        at android.view.View.draw(View.java:18321)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3946)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3732)
        at android.view.View.updateDisplayListIfDirty(View.java:17532)
        at android.view.View.draw(View.java:18321)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3946)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3732)
        at android.view.View.draw(View.java:18562)
        at android.view.View.updateDisplayListIfDirty(View.java:17537)
        at android.view.View.draw(View.java:18321)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3946)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3732)
        at android.view.View.updateDisplayListIfDirty(View.java:17532)
        at android.view.View.draw(View.java:18321)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3946)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3732)
        at android.view.View.updateDisplayListIfDirty(View.java:17532)
        at android.view.View.draw(View.java:18321)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3946)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3732)
        at android.view.View.updateDisplayListIfDirty(View.java:17532)
        at android.view.View.draw(View.java:18321)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3946)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3732)
        at android.view.View.updateDisplayListIfDirty(View.java:17532)
        at android.view.View.draw(View.java:18321)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3946)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3732)
        at android.view.View.updateDisplayListIfDirty(View.java:17532)
        at android.view.View.draw(View.java:18321)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3946)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3732)
        at android.view.View.draw(View.java:18562)
        at com.android.internal.policy.DecorView.draw(DecorView.java:986)
        at android.view.View.updateDisplayListIfDirty(View.java:17537)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:713)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:719)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:827)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3204)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2991)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2579)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1569)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7296)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:930)
        at android.view.Choreographer.doCallbacks(Choreographer.java:705)
        at android.view.Choreographer.doFrame(Choreographer.java:640)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:916)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6816)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)

**Comment by halilozercan** [comment]
You cannnot play videos originated from UDP streams.
