### ISSUE TITLE
Does this library support URL redirect

### ISSUE THREAD

**Issue by pravinyo** [halilozercan/BetterVideoPlayer#70]
-###### Include the following:
- - Better Video Player version: `1.2.alpha1`
- - Device OS version: `6.0`
- - Device Manufacturer: `Lenovo`
- - Device Name: `Note k4`
-
I am loading videos which are in segments so i am using start and end to get that segment.When video is loading it is throwing FileNotFoundException and later plays the video so i would like to know more about this exception and what it means and how i can avoid it?
-
           String url  = mVideoUrl+mStart+"/"+end;

            bvp.reset();
            bvp.setSource(Uri.parse(url));
            bvp.setAutoPlay(true);

###### Actual Result
I/MovieWatchingActivity: Completed: Loading next segment
E/MediaPlayer: setDataSource: IOException! uri=video_url_path?t=start/end
    java.io.FileNotFoundException: No content provider: video_url_path?t=start/end
        at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1123)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:958)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:881)
        at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1018)
        at com.halilibo.bettervideoplayer.BetterVideoPlayer.prepare(BetterVideoPlayer.java:393)
        at com.halilibo.bettervideoplayer.BetterVideoPlayer.setSource(BetterVideoPlayer.java:275)
        at MovieWatchingActivity.loadVideoPlayer(MovieWatchingActivity.java:240)
        at MovieWatchingActivity.access$500(MovieWatchingActivity.java:29)
        at MovieWatchingActivity$3.onCompletion(MovieWatchingActivity.java:157)
        at com.halilibo.bettervideoplayer.BetterVideoPlayer.onCompletion(BetterVideoPlayer.java:800)
        at android.media.MediaPlayer$EventHandler.handleMessage(MediaPlayer.java:3049)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:5776)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

**Comment by halilozercan** [comment]
In terms of HTTP and codec capabilities, library is just a wrapper around stock Android MediaPlayer API. I believe it should support url redirect but cant give a definite answer.
