### ISSUE TITLE
[Bug] Encoded video URLs crash the app.

### ISSUE THREAD

**Issue by autovalue** [halilozercan/BetterVideoPlayer#8]
With a URL such as: https://github.com/halilozercan/BetterVideoPlayer/random-encoded-url.mp4%3Ffoo%3Dbar%26bar%3Dnaz%5Bhello%5D

Because the `LOG` method uses a String.format, it tries to format the %s in the video/subtitle URLs and throws an exception.

**Comment by halilozercan** [comment]
LOG method should be replaced by Log.d in ```prepare``` method.

**Comment by billionbucks** [comment]
so? how can we fix it?

**Comment by autovalue** [comment]
My temporary solution was to encode the BetterVideoPlayer urls.

But @halilozercan's solution would work as well.

**Comment by halilozercan** [comment]
I'm sorry that I have been between so many things about my education as of lately. I'm adding your suggestions and fixing so the bugs but do not have time to commit the changes.

**Comment by zizoh** [comment]
This issue still exists. Video url I have contains "%2F" and app crashes with:

java.util.UnknownFormatConversionException: Conversion = 'F'
        at java.util.Formatter$FormatSpecifier.conversion(Formatter.java:2781)
        at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2811)
        at java.util.Formatter$FormatSpecifierParser.<init>(Formatter.java:2624)
        at java.util.Formatter.parse(Formatter.java:2557)
        at java.util.Formatter.format(Formatter.java:2504)
        at java.util.Formatter.format(Formatter.java:2458)
        at java.lang.String.format(String.java:2842)
        at com.halilibo.bvpkotlin.BetterVideoPlayer$Companion.log(BetterVideoPlayer.kt:1072)
