### ISSUE TITLE
Crash on android 6.0

### ISSUE THREAD

**Issue by thuan09878** [halilozercan/BetterVideoPlayer#94]
-###### Include the following:
- - Better Video Player version: `kotlin-SNAPSHOT`
- - Device OS version: `6.0`
- - Device Manufacturer: `Google`
- - Device Name: `Nexus 5`
-
-Also, please wrap Java with correct syntax highlighting.
- url = "https://video.twimg.com/ext_tw_video/1117320833159041025/pu/vid/720x720/piTPVBdEsAuatXVV.mp4?tag=8"
- videoPlayer.setSource(Uri.parse(url))
  videoPlayer.enableSwipeGestures()
  videoPlayer.getToolbar().title = ""
        videoPlayer.getToolbar()
            .setNavigationIcon(androidx.appcompat.R.drawable.abc_ic_ab_back_material)
        videoPlayer.getToolbar().setNavigationOnClickListener { onBackPressed() }

        // Set up the user interaction to manually show or hide the system UI.
        videoPlayer.setOnClickListener {
            toggle()
        }
-###### Reproduction Steps
- Open the Activity with the video player
-###### Expected Result
- Play the video 
-###### Actual Result
- App crashes
05-27 16:52:13.007 24733-24733/com.avd.videodownloader.all E/MediaPlayer: Error (1,-2147483648)
05-27 16:52:13.012 24733-24733/com.avd.videodownloader.all E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.avd.videodownloader.all, PID: 24733
    java.lang.RuntimeException: java.lang.Exception: Preparation/playback error (1): Unknown error
        at com.halilibo.bvpkotlin.BetterVideoPlayer.throwError(BetterVideoPlayer.kt:1049)
        at com.halilibo.bvpkotlin.BetterVideoPlayer.onError(BetterVideoPlayer.kt:858)
        at android.media.MediaPlayer$EventHandler.handleMessage(MediaPlayer.java:2874)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: java.lang.Exception: Preparation/playback error (1): Unknown error

* It works on android 8.0 but crashes on 6.0 device. What can I do with this? 
Thank you.

**Comment by hibittushah** [comment]
Hello @thuan09878 
Have you solved this issue ?
